// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2
// source: cart_product.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createCartProduct = `-- name: CreateCartProduct :one
INSERT INTO cart_products (
  product_id,
  user_id,
  quantity
) VALUES (
  $1,
  $2,
  $3
) RETURNING id, product_id, user_id, quantity
`

type CreateCartProductParams struct {
	ProductID uuid.UUID `json:"product_id"`
	UserID    uuid.UUID `json:"user_id"`
	Quantity  int32     `json:"quantity"`
}

func (q *Queries) CreateCartProduct(ctx context.Context, arg CreateCartProductParams) (CartProduct, error) {
	row := q.db.QueryRowContext(ctx, createCartProduct, arg.ProductID, arg.UserID, arg.Quantity)
	var i CartProduct
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.UserID,
		&i.Quantity,
	)
	return i, err
}

const getCartProductsByUserId = `-- name: GetCartProductsByUserId :many
SELECT id, product_id, user_id, quantity FROM cart_products
WHERE user_id = $1
`

func (q *Queries) GetCartProductsByUserId(ctx context.Context, userID uuid.UUID) ([]CartProduct, error) {
	rows, err := q.db.QueryContext(ctx, getCartProductsByUserId, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CartProduct{}
	for rows.Next() {
		var i CartProduct
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.UserID,
			&i.Quantity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const truncateCartProductsTable = `-- name: TruncateCartProductsTable :exec
TRUNCATE TABLE cart_products CASCADE
`

func (q *Queries) TruncateCartProductsTable(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, truncateCartProductsTable)
	return err
}
