/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Next Bazaar API
 * OpenAPI spec version: 0.0.1
 */

export interface ApiListProductsResponseMeta {
  page_count?: number;
  page_id?: number;
  page_size?: number;
  total_count?: number;
}
