/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Next Bazaar API
 * OpenAPI spec version: 0.0.1
 */
import type { ApiProductResponse } from "./apiProductResponse";
import type { ApiListProductsResponseMeta } from "./apiListProductsResponseMeta";

export interface ApiListProductsResponse {
  data?: ApiProductResponse[];
  meta?: ApiListProductsResponseMeta;
}
