/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Next Bazaar API
 * OpenAPI spec version: 0.0.1
 */

export interface ApiProductResponse {
  category?: string;
  description?: string;
  id?: string;
  image_url?: string;
  name?: string;
  price?: string;
  seller?: string;
  stock_quantity?: number;
}
