/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Next Bazaar API
 * OpenAPI spec version: 0.0.1
 */
import type { CartDomainCartProductResponse } from './cartDomainCartProductResponse'

export interface CartDomainCartResponse {
  products?: CartDomainCartProductResponse[]
  shipping?: string
  subtotal?: string
  tax?: string
  total?: string
}
