/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Next Bazaar API
 * OpenAPI spec version: 0.0.1
 */
import type { ProductDomainListProductsResponseMeta } from './productDomainListProductsResponseMeta'
import type { ProductDomainProductResponse } from './productDomainProductResponse'

export interface ProductDomainListProductsResponse {
  data?: ProductDomainProductResponse[]
  meta?: ProductDomainListProductsResponseMeta
}
