/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Next Bazaar API
 * OpenAPI spec version: 0.0.1
 */

export interface ProductDomainAddProductRequest {
  category_id: string
  description?: string
  image_url?: string
  name: string
  price: string
  stock_quantity: number
}
