/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Next Bazaar API
 * OpenAPI spec version: 0.0.1
 */
import type { ProductDomainListProductCategoriesResponseMeta } from './productDomainListProductCategoriesResponseMeta'
import type { ProductDomainProductCategoryResponse } from './productDomainProductCategoryResponse'

export interface ProductDomainListProductCategoriesResponse {
  data?: ProductDomainProductCategoryResponse[]
  meta?: ProductDomainListProductCategoriesResponseMeta
}
