/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Next Bazaar API
 * OpenAPI spec version: 0.0.1
 */

export interface UserDomainRegisterRequest {
  email: string
  name: string
  password: string
}
