/**
 * Generated by orval v6.15.0 🍺
 * Do not edit manually.
 * Next Bazaar API
 * OpenAPI spec version: 0.0.1
 */

export interface UserDomainUpdatePasswordRequest {
  new_password: string
  old_password: string
}
