name: ci-api-test

on:
  push:
    branches:
      - "main"
    paths:
      - "api/**"
  pull_request:
    branches:
      - "main"
    paths:
      - "api/**"

defaults:
  run:
    working-directory: api

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: next-bazaar
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.20"

      - name: Install golang-migrate
        run: |
          curl -L https://github.com/golang-migrate/migrate/releases/download/v4.15.2/migrate.linux-amd64.tar.gz | tar xvz
          sudo mv migrate /usr/bin/
          which migrate

      - name: Run migrations
        run: make test-migrateup

      - name: Pull testcontainers/ryuk:0.5.1
        run: docker pull testcontainers/ryuk:0.5.1

      - name: Test
        run: make test
