name: ci-api-test

on:
  push:
    branches:
      - "main"
    paths:
      - "api/**"
  pull_request:
    branches:
      - "main"
    paths:
      - "api/**"

defaults:
  run:
    working-directory: api

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.20"

      - name: Install golang-migrate
        run: |
          curl -L https://github.com/golang-migrate/migrate/releases/download/v4.15.2/migrate.linux-amd64.tar.gz | tar xvz
          sudo mv migrate /usr/bin/
          which migrate

      - name: Run migrations
        run: make test-migrateup

      - name: Pull testcontainers/ryuk:0.4.0
        run: docker pull testcontainers/ryuk:0.4.0

      - name: Test
        run: make test
